import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import rightpane from "../assets/RightPane.jpg";
import { url } from "inspector";
import logo from "../assets/logo.png";
import Input from "../Components/InputComponent/Input";
import Button from "../Components/ButtonComponent/Button";
const Home: NextPage = () => {
  return (
    <div className={styles.maincontainer}>
      <Head>
        <title>login page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="" href="" />
      </Head>
      <div className={styles.firstcontainer}>
        <div className={styles.secondcontainer}>
          <Image src={logo} width={20} height={20} objectFit="contain"></Image>
          <h1 style={{ fontSize: "20px", textAlign: "center" }}>
            Thank you for choosing us
          </h1>
          <p style={{ textAlign: "center", fontSize: "16px" }}>
            Welcome back!Please enter your details below
          </p>
          <div className={styles.inputcontainer}>
            <Input type="text" placeholder="Enter your email" />
            <Input type="password" placeholder="Password" />
          </div>
          <Button text="Log In" classname="login" />
          <div className={styles.mainor}>
            <div className={styles.or}></div>
            <h1 className={styles.ortxt}>OR</h1>
            <div className={styles.or}></div>
          </div>
          <Button text="Log In with Google" classname="google" />
        </div>

        <Image
          src={rightpane}
          width={390}
          height={510}
          objectFit="contain"
          className={styles.bg}
        ></Image>
      </div>
    </div>
  );
};

export default Home;
